name: Cypress Test CI

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  install-command: npm install cypress --save-dev, npm install -D cypress-xpath
                  command: npm cypress run --record --key c0911386-20a9-47be-bd48-bfd0b0133258
